# Generated by Django 4.2.3 on 2023-08-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_userguidesimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_price',
            field=models.IntegerField(blank=True, verbose_name='Task price'),
        ),
    ]
