# Generated by Django 4.2.3 on 2023-08-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_tasks_task_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_status',
            field=models.BooleanField(default=False, verbose_name='Task status'),
        ),
    ]
