# Generated by Django 4.2.3 on 2023-08-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_tasks_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_progress',
            field=models.BooleanField(default=False, verbose_name='Task progress'),
        ),
    ]
