# Generated by Django 4.2.3 on 2023-08-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_tasks_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_price_equipment',
            field=models.IntegerField(default=0, verbose_name='Equipment price'),
        ),
    ]
