# Generated by Django 4.2.3 on 2023-08-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_tasks_task_price_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task_price',
            new_name='task_price_job',
        ),
    ]
