# Generated by Django 4.2.3 on 2023-08-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authorisation', '0002_rename_customuseruser_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='CustomUserUser',
        ),
    ]
