# Generated by Django 4.2.3 on 2023-08-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0005_alter_customuseruser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuseruser',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
    ]
