# Generated by Django 4.2.3 on 2023-08-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0006_alter_customuseruser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuseruser',
            name='usertg_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='usertg_id'),
        ),
        migrations.AlterField(
            model_name='customuseruser',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
