# Generated by Django 4.2.3 on 2023-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_name', models.CharField(max_length=80, verbose_name='Name')),
                ('company_name', models.CharField(max_length=50, verbose_name='Manufacturer')),
                ('type_el', models.CharField(max_length=50, verbose_name='Category')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('availability', models.BooleanField(default=True, verbose_name='Availability')),
                ('image_item', models.ImageField(default='no_image.jpg', upload_to='service/images/shop/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Spare part',
                'verbose_name_plural': 'Spare parts',
            },
        ),
    ]
