# Generated by Django 4.2.3 on 2023-08-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsupply',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
